#!/bin/sh
alias \
    cd='fn_cd' \
    ka="killall" \
    mkd="mkdir -pv" \
    trem="transmission-remote" \
    e="$EDITOR" \
    v="$EDITOR" \
    gua="git remote | xargs -L1 git push --all" \
    gs='git status' \
    grep="grep --color=auto" \
    la='ls -F' \
    sl="ls -F" \
    lsa='ls -A' \
    ll='ls -l' \
    lsl='ls -l' \
    diff="diff --color=auto" \
    ccat="highlight --out-format=ansi" \
    yt="youtube-dl --add-metadata -i -o '%(upload_date)s-%(title)s.%(ext)s'" \
    yta="yt -x -f bestaudio/best" \
    YT="youtube-viewer" \
    cfv="$EDITOR $HOME/.vimrc" \
    cfz="$EDITOR $HOME/.zshrc" \
    cfa="$EDITOR $HOME/.aliasrc" \
    all="docker ps -a -q" \
    python='python3.8 -q' \
    python3='python3.8 -q' \
    weather='curl wttr.in' \
    info='info --vi-keys' \
    tmux="tmux -f ${DOTFILES}/tmuxrc"
    ta="tmux attach"


# Use neovim for vim if present.
command -v nvim >/dev/null && alias vim="nvim" vimdiff="nvim -d" alias vi="nvim"



# start async matrix with Japanese katakana characters
# source: https://github.com/will8211/unimatrix
# sudo curl -L https://raw.githubusercontent.com/will8211/unimatrix/master/unimatrix.py -o /usr/local/bin/unimatrix
# sudo chmod a+rx /usr/local/bin/unimatrix
alias matrix='unimatrix -naf -s 96 -l k'

# Verbosity and settings that you pretty much just always are going to want.
alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -v" \
	mkd="mkdir -pv" \
	yta="yt -x -f bestaudio/best"

# Colorize commands when possible.
alias \
	grep="grep --color=auto" \
    egrep="egrep --color=auto" \
    fgrep="fgrep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi"

# These common commands are just too long! Abbreviate them.
alias \
	ka="killall" \
	trem="transmission-remote" \
	sdn="sudo shutdown -h now" \
	e="$EDITOR" \
	v="$EDITOR" \

alias date='date +"%F %T%:z"'
# e.g. `2019-06-05 13:41:32-07:00`

# SCHOOL SHORTCUTS

# These single shortcuts jump me to the right directory
alias \
    web="cd ~/projects/itp303/" \
    comp="cd ~/projects/itp439/" \
    ai="cd ~/projects/ai/" \
    os="cd ~/projects/cs350/project-4-cdurham_lee344"
    osd="cd ~/projects/cs350-docker"


# DEVELOPMENT

# start CS356 VM in background
alias fuckvms='VBoxHeadless -s CS356 &'

alias vmssh='ssh -p 3022 trojan@127.0.0.1'

# dump todo lists into a folder
# TODO: make into a script
alias todo='grep -Ri "todo[:\ ]" .'

# start cs-104 docker env in cs104 directory and start working in /home/work
alias cpup='docker run -ti -v "$HOME/cs104/":/home/work -w /home/work/ csci104 /bin/bash'

alias cphere='docker run -ti -v "$(pwd)":/home/work -w /home/work/ csci104 /bin/bash'

# start cs-104 docker image in cs104 directory
# alias cpstartup='docker run -v "$HOME/cs104/":/work/ -dt --cap-add SYS_PTRACE --security-opt seccomp=unconfined --name csci104 csci104'
alias cpstartup='docker run -it --cap-add=SYS_PTRACE --security-opt seccomp=unconfined -v "$(pwd)":/home/work -w /home/work csci104 /bin/bash'

# start up itp compiler development vm
alias compiler='docker run -it -v "$ITP439":/root/uscc/code -w /root/uscc/code compiler /bin/bash'

# compile a c++ program with ALL the fucking warnings
#   usage: compile <FILE>.cpp OR compile <FILE>.cpp -o <FILE>.o
alias compile='g++ --std=c++11 -Wextra -pedantic -Wall -Wshadow
            \ -Wsign-conversion -Wsign-promo -Wstrict-null-sentinel -Werror'

alias supos='docker run -it --cap-add=SYS_PTRACE --security-opt seccomp=unconfined -v "$HOME/projects/cs350/":/root -w /root --name cs350 cs350_32 /bin/bash'

alias osup='docker run -it --cap-add=SYS_PTRACE --security-opt seccomp=unconfined  -v "$HOME/projects/cs350/":/root -w /root cs350_32 /bin/bash'

alias oshere='docker run -it --cap-add=SYS_PTRACE --security-opt seccomp=unconfined  -v "$(pwd)":/root -w /root cs350_32 /bin/bash'

alias sandbox='cd ~/projects/sandbox/'
