#!/bin/bash
dir="projects/practice/cpp/leetcode"
if [ $# -lt 1 ]; then echo "Usage $0 <problem number>";exit 1;
elif [ ! -f "$HOME/$dir/$1.cpp" ]; then cp "$HOME/$dir/0.cpp" "$HOME/$dir/$1.cpp";fi
cd "$HOME/$dir" && "$EDITOR" "$1.cpp"
