#!/bin/bash

# slow, working version of shell script

if [ $# -lt 1 ];
then echo "Usage $0 <problem number>";
    exit 1;
fi;

if [ -z "$PRACTICE_CPP_LEETCODE" ];
    then echo "PRACTICE_CPP_LEETCODE var not set";
    exit 1;
fi;

if [ ! -f "$PRACTICE_CPP_LEETCODE/$1.cpp" ];
then cp "$PRACTICE_CPP_LEETCODE/leetcode_template.cpp" "$PRACTICE_CPP_LEETCODE/$1.cpp";
fi;
cd "$PRACTICE_CPP_LEETCODE"
nvim "$1.cpp"
